title: Start Gigging San Antonio - A yellow pages for gig related work curated by the City of San Antonio
email: contact@88pixels.com
description: "Yellow pages for Gig work"
url: ""
destination: public
exclude: [public, Rakefile, README.md]
markdown: kramdown

sass:
  style:    :compressed
  sass_dir: assets/stylesheets
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages:  ['en', 'es']
language_default:   'en'
exclude_from_localizations: ["javascript", "images", "css"]
